Trivy defauls

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -55,52 +55,62 @@ unit-test:
     - docker pull $CI_REGISTRY_IMAGE/frontend:$CI_COMMIT_REF_NAME
     - docker-compose --profile unittest up --build --abort-on-container-exit
 
-# Trivy Scans
-frontend_scan:
+# Trivy Scan mit defauls
+container_scanning:
   stage: scan
-  before_script:
-    - echo $CI_REGISTRY
-    - echo $CI_REGISTRY_USER
-    - echo $CI_REGISTRY_PASSWORD
-    - echo $CI_REGISTRY_IMAGE
-    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
-    - |
-      if [ $? -ne 0 ]; then
-        echo "Docker login failed"
-        exit 1
-      fi
   variables:
     SECURE_LOG_LEVEL: 'debug'
-    CS_IMAGE: 'registry.mygit.th-deg.de/mimigma/mimigma/frontend:$CI_COMMIT_REF_NAME'
+    CS_IMAGE: 'registry.mygit.th-deg.de/mimigma/mimigma/backend'
     CS_DOCKERFILE_PATH: './frontend/Dockerfile'
     GIT_STRATEGY: 'fetch'
-  script:
-    - echo $CS_IMAGE
-    - docker pull $CS_IMAGE
-    - |
-      if [ $? -ne 0 ]; then
-        echo "Docker pull failed"
-        exit 1
-      fi
-    - docker images
-    - trivy image --exit-code 1 --severity HIGH,CRITICAL $CS_IMAGE
 
-# backend_scan:
+# Trivy Scans
+# frontend_scan:
 #   stage: scan
 #   before_script:
-#   - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
+#     - echo "does this work?" 
+#     - echo $CI_REGISTRY_USER
+#     - echo $CI_REGISTRY_PASSWORD
+#     - echo $CI_REGISTRY_IMAGE
+#     - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
+#     - |
+#       if [ $? -ne 0 ]; then
+#         echo "Docker login failed"
+#         exit 1
+#       fi
 #   variables:
 #     SECURE_LOG_LEVEL: 'debug'
-#     CS_IMAGE: '$CI_REGISTRY_IMAGE/backend:$CI_COMMIT_REF_NAME'
-#     CS_DOCKERFILE_PATH: './backend/Dockerfile'
+#     CS_IMAGE: 'registry.mygit.th-deg.de/mimigma/mimigma/frontend:$CI_COMMIT_REF_NAME'
+#     CS_DOCKERFILE_PATH: './frontend/Dockerfile'
 #     GIT_STRATEGY: 'fetch'
 #   script:
+#     - echo $CS_IMAGE
+#     - docker pull $CS_IMAGE
+#     - |
+#       if [ $? -ne 0 ]; then
+#         echo "Docker pull failed"
+#         exit 1
+#       fi
+#     - docker images
 #     - trivy image --exit-code 1 --severity HIGH,CRITICAL $CS_IMAGE
 # 
-cleanup:
-  stage: cleanup
-  image: docker:26.0.1
-  script:
-    - docker rmi $CI_REGISTRY_IMAGE/frontend:$CI_COMMIT_REF_NAME;
-    - docker rmi $CI_REGISTRY_IMAGE/backend:$CI_COMMIT_REF_NAME;
-  when: always
+# # backend_scan:
+# #   stage: scan
+# #   before_script:
+# #   - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
+# #   variables:
+# #     SECURE_LOG_LEVEL: 'debug'
+# #     CS_IMAGE: '$CI_REGISTRY_IMAGE/backend:$CI_COMMIT_REF_NAME'
+# #     CS_DOCKERFILE_PATH: './backend/Dockerfile'
+# #     GIT_STRATEGY: 'fetch'
+# #   script:
+# #     - trivy image --exit-code 1 --severity HIGH,CRITICAL $CS_IMAGE
+# # 
+# cleanup:
+#   stage: cleanup
+#   image: docker:26.0.1
+#   script:
+#     - docker rmi $CI_REGISTRY_IMAGE/frontend:$CI_COMMIT_REF_NAME;
+#     - docker rmi $CI_REGISTRY_IMAGE/backend:$CI_COMMIT_REF_NAME;
+#   when: always
+# 
