Revert to commit ff6bafff since pipeline builds take forever

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -1,27 +1,20 @@
 include:
   - template: Jobs/SAST.gitlab-ci.yml
 
-default:
-  image: docker:26.0.1
-  services:
-    - docker:26.0.1-dind
-  before_script:
-    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
-
-.build_test_scan_defaults:
-  before_script:
-    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
-
 stages:
   - build
+  - scan 
   - test
-  - scan
   - cleanup
 
 # Build and push the frontend image
 build_frontend:
   stage: build
-  extends: .build_test_scan_defaults
+  image: docker:26.0.1
+  services:
+    - docker:26.0.1-dind
+  before_script:
+    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
   script:
     - docker build -t $CI_REGISTRY_IMAGE/frontend:$CI_COMMIT_REF_NAME -f ./frontend/Dockerfile ./frontend
     - docker push $CI_REGISTRY_IMAGE/frontend:$CI_COMMIT_REF_NAME
@@ -29,34 +22,29 @@ build_frontend:
 # Build and push the backend image
 build_backend:
   stage: build
-  extends: .build_test_scan_defaults
+  image: docker:26.0.1
+  services:
+    - docker:26.0.1-dind
+  before_script:
+    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
   script:
     - docker build -t $CI_REGISTRY_IMAGE/backend:$CI_COMMIT_REF_NAME -f ./backend/Dockerfile ./backend
     - docker push $CI_REGISTRY_IMAGE/backend:$CI_COMMIT_REF_NAME
 
-e2e_test:
-  stage: test
-  extends: .build_test_scan_defaults
-  script:
-    - docker-compose rm -f
-    - docker pull $CI_REGISTRY_IMAGE/frontend:$CI_COMMIT_REF_NAME
-    - docker-compose --profile e2etest up --build --abort-on-container-exit
-
-unit_test:
-  stage: test
-  extends: .build_test_scan_defaults
-  script:
-    - docker pull $CI_REGISTRY_IMAGE/frontend:$CI_COMMIT_REF_NAME
-    - docker-compose --profile unittest up --build --abort-on-container-exit
-
 # Trivy Scan - modify CS_IMAGE depending which image you want to scan
 backend_scan:
   stage: scan
-  extends: .build_test_scan_defaults
+  image: docker:26.0.1
+  services:
+    - docker:26.0.1-dind
+  before_script:
+    - apk add curl
+    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
   variables:
+    SECURE_LOG_LEVEL: 'debug'
+    GIT_STRATEGY: 'fetch'
     CS_IMAGE: 'registry.mygit.th-deg.de/mimigma/mimigma/backend:dev2'
   script:
-    - apk add curl
     - curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin v0.52.2
     - trivy image $CS_IMAGE | tee scanning-report.txt
   artifacts:
@@ -65,20 +53,93 @@ backend_scan:
 
 frontend_scan:
   stage: scan
-  extends: .build_test_scan_defaults
+  image: docker:26.0.1
+  services:
+    - docker:26.0.1-dind
+  before_script:
+    - apk add curl
+    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
   variables:
+    SECURE_LOG_LEVEL: 'debug'
+    GIT_STRATEGY: 'fetch'
     CS_IMAGE: 'registry.mygit.th-deg.de/mimigma/mimigma/frontend:dev2'
   script:
-    - apk add curl
     - curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin v0.52.2
     - trivy image $CS_IMAGE | tee scanning-report.txt
   artifacts:
     reports:
       container_scanning: scanning-report.txt
 
-cleanup:
-  stage: cleanup
+2e-test:
+  stage: test
+  image: docker:26.0.1-dind  # Use the dind image for running Docker commands
+  services:
+    - docker:26.0.1-dind
+  before_script:
+    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
   script:
-    - docker rmi $CI_REGISTRY_IMAGE/frontend:$CI_COMMIT_REF_NAME
-    - docker rmi $CI_REGISTRY_IMAGE/backend:$CI_COMMIT_REF_NAME
-  when: always
+    - docker-compose rm -f
+    - docker pull $CI_REGISTRY_IMAGE/frontend:$CI_COMMIT_REF_NAME
+    - docker-compose --profile e2etest up --build --abort-on-container-exit
+
+unit-test:
+  stage: test
+  image: docker:26.0.1-dind  # Use the dind image for running Docker commands
+  services:
+    - docker:26.0.1-dind
+  before_script:
+    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
+  script:
+    - docker pull $CI_REGISTRY_IMAGE/frontend:$CI_COMMIT_REF_NAME
+    - docker-compose --profile unittest up --build --abort-on-container-exit
+
+# Trivy Scans
+# frontend_scan:
+#   stage: scan
+#   before_script:
+#     - echo "does this work?" 
+#     - echo $CI_REGISTRY_USER
+#     - echo $CI_REGISTRY_PASSWORD
+#     - echo $CI_REGISTRY_IMAGE
+#     - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
+#     - |
+#       if [ $? -ne 0 ]; then
+#         echo "Docker login failed"
+#         exit 1
+#       fi
+#   variables:
+#     SECURE_LOG_LEVEL: 'debug'
+#     CS_IMAGE: 'registry.mygit.th-deg.de/mimigma/mimigma/frontend:$CI_COMMIT_REF_NAME'
+#     CS_DOCKERFILE_PATH: './frontend/Dockerfile'
+#     GIT_STRATEGY: 'fetch'
+#   script:
+#     - echo $CS_IMAGE
+#     - docker pull $CS_IMAGE
+#     - |
+#       if [ $? -ne 0 ]; then
+#         echo "Docker pull failed"
+#         exit 1
+#       fi
+#     - docker images
+#     - trivy image --exit-code 1 --severity HIGH,CRITICAL $CS_IMAGE
+# 
+# # backend_scan:
+# #   stage: scan
+# #   before_script:
+# #   - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
+# #   variables:
+# #     SECURE_LOG_LEVEL: 'debug'
+# #     CS_IMAGE: '$CI_REGISTRY_IMAGE/backend:$CI_COMMIT_REF_NAME'
+# #     CS_DOCKERFILE_PATH: './backend/Dockerfile'
+# #     GIT_STRATEGY: 'fetch'
+# #   script:
+# #     - trivy image --exit-code 1 --severity HIGH,CRITICAL $CS_IMAGE
+# # 
+# cleanup:
+#   stage: cleanup
+#   image: docker:26.0.1
+#   script:
+#     - docker rmi $CI_REGISTRY_IMAGE/frontend:$CI_COMMIT_REF_NAME;
+#     - docker rmi $CI_REGISTRY_IMAGE/backend:$CI_COMMIT_REF_NAME;
+#   when: always
+# 
