formatting

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -64,7 +64,11 @@ frontend_scan:
     - echo "CI_REGISTRY_PASSWORD: $CI_REGISTRY_PASSWORD"
     - echo "CI_REGISTRY_IMAGE: $CI_REGISTRY_IMAGE"
     - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
-    - if [ $? -ne 0 ]; then echo "Docker login failed"; exit 1; fi
+    - |
+      if [ $? -ne 0 ]; then
+        echo "Docker login failed"
+        exit 1
+      fi
   variables:
     SECURE_LOG_LEVEL: 'debug'
     CS_IMAGE: 'registry.mygit.th-deg.de/mimigma/mimigma/frontend:$CI_COMMIT_REF_NAME'
@@ -73,7 +77,11 @@ frontend_scan:
   script:
     - echo "CS_IMAGE: $CS_IMAGE"
     - docker pull $CS_IMAGE
-    - if [ $? -ne 0 ]; then echo "Docker pull failed"; exit 1; fi
+    - |
+      if [ $? -ne 0 ]; then
+        echo "Docker pull failed"
+        exit 1
+      fi
     - docker images
     - trivy image --exit-code 1 --severity HIGH,CRITICAL $CS_IMAGE
 
